### ISSUE TITLE
Handle get __file__ (client asks for file from server)

### ISSUE THREAD

**Issue by ekelen** [pbandb/ft_p#31]
- [x] Sujet: `get _file_ : download the file _file_ from the server to the client.`

For client:
- [x] Test with enormous file
- [x] Test with empty file
- [x] Test with tiny, medium, normal buf
- [x] Test with binary
- [x] Test with file len same as buf size

For server:
- [x] Test with file len same as buf size
- [x] Test with server tiny, medium, normal buf

**Comment by Failte21** [comment]
- [x] server
- [ ] client
